import {
  Award,
  Bell,
  Bookmark,
  BookOpen,
  Building2,
  Calendar,
  Camera,
  Car,
  Clock,
  Coffee,
  CreditCard,
  Download,
  FileText,
  Folder,
  Gift,
  Globe,
  Headphones,
  Heart,
  Home,
  Image,
  Link2,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Mic,
  Music,
  PenLine,
  Phone,
  Play,
  Send,
  Settings,
  Share2,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Tag,
  Ticket,
  User,
  Users,
  Utensils,
  Video,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  link: Link2,
  mail: Mail,
  phone: Phone,
  calendar: Calendar,
  pin: MapPin,
  bag: ShoppingBag,
  music: Music,
  video: Video,
  camera: Camera,
  file: FileText,
  star: Star,
  heart: Heart,
  user: User,
  users: Users,
  gear: Settings,
  tools: Wrench,
  cart: ShoppingCart,
  message: MessageCircle,
  globe: Globe,
  play: Play,
  download: Download,
  ticket: Ticket,
  home: Home,
  spark: Sparkles,
  mic: Mic,
  book: BookOpen,
  gift: Gift,
  folder: Folder,
  clock: Clock,
  image: Image,
  card: CreditCard,
  lock: Lock,
  send: Send,
  bell: Bell,
  tag: Tag,
  pen: PenLine,
  building: Building2,
  food: Utensils,
  coffee: Coffee,
  car: Car,
  headphones: Headphones,
  phone2: Smartphone,
  award: Award,
  share: Share2,
  bookmark: Bookmark,
  zap: Zap,
};

export function BioGlyph({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name];
  if (!Icon) return null;
  return <Icon className={className} aria-hidden />;
}
