/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ControlRouteImport } from './routes/control'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ControlIndexRouteImport } from './routes/control/index'
import { Route as ControlAuditRouteImport } from './routes/control/audit'
import { Route as ControlChatRouteImport } from './routes/control/chat'
import { Route as ControlCustomersRouteImport } from './routes/control/customers'
import { Route as ControlDomainRouteImport } from './routes/control/domain'
import { Route as ControlEmailRouteImport } from './routes/control/email'
import { Route as ControlIntegrationsRouteImport } from './routes/control/integrations'
import { Route as ControlLinksRouteImport } from './routes/control/links'
import { Route as ControlParametersRouteImport } from './routes/control/parameters'
import { Route as ControlRequestsRouteImport } from './routes/control/requests'
import { Route as ControlResourcesRouteImport } from './routes/control/resources'
import { Route as ControlShortsRouteImport } from './routes/control/shorts'
import { Route as ControlStatsRouteImport } from './routes/control/stats'
import { Route as ControlWorkspaceRouteImport } from './routes/control/workspace'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCardsResourceIdRouteImport } from './routes/api/cards/$resourceId'
import { Route as ApiFilesResourceIdRouteImport } from './routes/api/files/$resourceId'
import { Route as ApiV1ShortsRouteImport } from './routes/api/v1/shorts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlIndexRoute = ControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlRoute,
} as any)
const ControlAuditRoute = ControlAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ControlRoute,
} as any)
const ControlChatRoute = ControlChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ControlRoute,
} as any)
const ControlCustomersRoute = ControlCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ControlRoute,
} as any)
const ControlDomainRoute = ControlDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => ControlRoute,
} as any)
const ControlEmailRoute = ControlEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ControlRoute,
} as any)
const ControlIntegrationsRoute = ControlIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ControlRoute,
} as any)
const ControlLinksRoute = ControlLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => ControlRoute,
} as any)
const ControlParametersRoute = ControlParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => ControlRoute,
} as any)
const ControlRequestsRoute = ControlRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ControlRoute,
} as any)
const ControlResourcesRoute = ControlResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ControlRoute,
} as any)
const ControlShortsRoute = ControlShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => ControlRoute,
} as any)
const ControlStatsRoute = ControlStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ControlRoute,
} as any)
const ControlWorkspaceRoute = ControlWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ControlRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsResourceIdRoute = ApiCardsResourceIdRouteImport.update({
  id: '/api/cards/$resourceId',
  path: '/api/cards/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesResourceIdRoute = ApiFilesResourceIdRouteImport.update({
  id: '/api/files/$resourceId',
  path: '/api/files/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ShortsRoute = ApiV1ShortsRouteImport.update({
  id: '/api/v1/shorts',
  path: '/api/v1/shorts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/control': typeof ControlRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/chat': typeof ControlChatRoute
  '/control/customers': typeof ControlCustomersRoute
  '/control/domain': typeof ControlDomainRoute
  '/control/email': typeof ControlEmailRoute
  '/control/integrations': typeof ControlIntegrationsRoute
  '/control/links': typeof ControlLinksRoute
  '/control/parameters': typeof ControlParametersRoute
  '/control/requests': typeof ControlRequestsRoute
  '/control/resources': typeof ControlResourcesRoute
  '/control/shorts': typeof ControlShortsRoute
  '/control/stats': typeof ControlStatsRoute
  '/control/workspace': typeof ControlWorkspaceRoute
  '/control/': typeof ControlIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cards/$resourceId': typeof ApiCardsResourceIdRoute
  '/api/files/$resourceId': typeof ApiFilesResourceIdRoute
  '/api/v1/shorts': typeof ApiV1ShortsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/chat': typeof ControlChatRoute
  '/control/customers': typeof ControlCustomersRoute
  '/control/domain': typeof ControlDomainRoute
  '/control/email': typeof ControlEmailRoute
  '/control/integrations': typeof ControlIntegrationsRoute
  '/control/links': typeof ControlLinksRoute
  '/control/parameters': typeof ControlParametersRoute
  '/control/requests': typeof ControlRequestsRoute
  '/control/resources': typeof ControlResourcesRoute
  '/control/shorts': typeof ControlShortsRoute
  '/control/stats': typeof ControlStatsRoute
  '/control/workspace': typeof ControlWorkspaceRoute
  '/control': typeof ControlIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cards/$resourceId': typeof ApiCardsResourceIdRoute
  '/api/files/$resourceId': typeof ApiFilesResourceIdRoute
  '/api/v1/shorts': typeof ApiV1ShortsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/control': typeof ControlRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/chat': typeof ControlChatRoute
  '/control/customers': typeof ControlCustomersRoute
  '/control/domain': typeof ControlDomainRoute
  '/control/email': typeof ControlEmailRoute
  '/control/integrations': typeof ControlIntegrationsRoute
  '/control/links': typeof ControlLinksRoute
  '/control/parameters': typeof ControlParametersRoute
  '/control/requests': typeof ControlRequestsRoute
  '/control/resources': typeof ControlResourcesRoute
  '/control/shorts': typeof ControlShortsRoute
  '/control/stats': typeof ControlStatsRoute
  '/control/workspace': typeof ControlWorkspaceRoute
  '/control/': typeof ControlIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cards/$resourceId': typeof ApiCardsResourceIdRoute
  '/api/files/$resourceId': typeof ApiFilesResourceIdRoute
  '/api/v1/shorts': typeof ApiV1ShortsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/control'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/uploads'
    | '/control/audit'
    | '/control/chat'
    | '/control/customers'
    | '/control/domain'
    | '/control/email'
    | '/control/integrations'
    | '/control/links'
    | '/control/parameters'
    | '/control/requests'
    | '/control/resources'
    | '/control/shorts'
    | '/control/stats'
    | '/control/workspace'
    | '/control/'
    | '/api/auth/$'
    | '/api/cards/$resourceId'
    | '/api/files/$resourceId'
    | '/api/v1/shorts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/uploads'
    | '/control/audit'
    | '/control/chat'
    | '/control/customers'
    | '/control/domain'
    | '/control/email'
    | '/control/integrations'
    | '/control/links'
    | '/control/parameters'
    | '/control/requests'
    | '/control/resources'
    | '/control/shorts'
    | '/control/stats'
    | '/control/workspace'
    | '/control'
    | '/api/auth/$'
    | '/api/cards/$resourceId'
    | '/api/files/$resourceId'
    | '/api/v1/shorts'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/control'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/uploads'
    | '/control/audit'
    | '/control/chat'
    | '/control/customers'
    | '/control/domain'
    | '/control/email'
    | '/control/integrations'
    | '/control/links'
    | '/control/parameters'
    | '/control/requests'
    | '/control/resources'
    | '/control/shorts'
    | '/control/stats'
    | '/control/workspace'
    | '/control/'
    | '/api/auth/$'
    | '/api/cards/$resourceId'
    | '/api/files/$resourceId'
    | '/api/v1/shorts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ControlRoute: typeof ControlRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCardsResourceIdRoute: typeof ApiCardsResourceIdRoute
  ApiFilesResourceIdRoute: typeof ApiFilesResourceIdRoute
  ApiV1ShortsRoute: typeof ApiV1ShortsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/': {
      id: '/control/'
      path: '/'
      fullPath: '/control/'
      preLoaderRoute: typeof ControlIndexRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/audit': {
      id: '/control/audit'
      path: '/audit'
      fullPath: '/control/audit'
      preLoaderRoute: typeof ControlAuditRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/chat': {
      id: '/control/chat'
      path: '/chat'
      fullPath: '/control/chat'
      preLoaderRoute: typeof ControlChatRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/customers': {
      id: '/control/customers'
      path: '/customers'
      fullPath: '/control/customers'
      preLoaderRoute: typeof ControlCustomersRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/domain': {
      id: '/control/domain'
      path: '/domain'
      fullPath: '/control/domain'
      preLoaderRoute: typeof ControlDomainRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/email': {
      id: '/control/email'
      path: '/email'
      fullPath: '/control/email'
      preLoaderRoute: typeof ControlEmailRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/integrations': {
      id: '/control/integrations'
      path: '/integrations'
      fullPath: '/control/integrations'
      preLoaderRoute: typeof ControlIntegrationsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/links': {
      id: '/control/links'
      path: '/links'
      fullPath: '/control/links'
      preLoaderRoute: typeof ControlLinksRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/parameters': {
      id: '/control/parameters'
      path: '/parameters'
      fullPath: '/control/parameters'
      preLoaderRoute: typeof ControlParametersRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/requests': {
      id: '/control/requests'
      path: '/requests'
      fullPath: '/control/requests'
      preLoaderRoute: typeof ControlRequestsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/resources': {
      id: '/control/resources'
      path: '/resources'
      fullPath: '/control/resources'
      preLoaderRoute: typeof ControlResourcesRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/shorts': {
      id: '/control/shorts'
      path: '/shorts'
      fullPath: '/control/shorts'
      preLoaderRoute: typeof ControlShortsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/stats': {
      id: '/control/stats'
      path: '/stats'
      fullPath: '/control/stats'
      preLoaderRoute: typeof ControlStatsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/workspace': {
      id: '/control/workspace'
      path: '/workspace'
      fullPath: '/control/workspace'
      preLoaderRoute: typeof ControlWorkspaceRouteImport
      parentRoute: typeof ControlRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards/$resourceId': {
      id: '/api/cards/$resourceId'
      path: '/api/cards/$resourceId'
      fullPath: '/api/cards/$resourceId'
      preLoaderRoute: typeof ApiCardsResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$resourceId': {
      id: '/api/files/$resourceId'
      path: '/api/files/$resourceId'
      fullPath: '/api/files/$resourceId'
      preLoaderRoute: typeof ApiFilesResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/shorts': {
      id: '/api/v1/shorts'
      path: '/api/v1/shorts'
      fullPath: '/api/v1/shorts'
      preLoaderRoute: typeof ApiV1ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ControlRouteChildren {
  ControlAuditRoute: typeof ControlAuditRoute
  ControlChatRoute: typeof ControlChatRoute
  ControlCustomersRoute: typeof ControlCustomersRoute
  ControlDomainRoute: typeof ControlDomainRoute
  ControlEmailRoute: typeof ControlEmailRoute
  ControlIntegrationsRoute: typeof ControlIntegrationsRoute
  ControlLinksRoute: typeof ControlLinksRoute
  ControlParametersRoute: typeof ControlParametersRoute
  ControlRequestsRoute: typeof ControlRequestsRoute
  ControlResourcesRoute: typeof ControlResourcesRoute
  ControlShortsRoute: typeof ControlShortsRoute
  ControlStatsRoute: typeof ControlStatsRoute
  ControlWorkspaceRoute: typeof ControlWorkspaceRoute
  ControlIndexRoute: typeof ControlIndexRoute
}

const ControlRouteChildren: ControlRouteChildren = {
  ControlAuditRoute: ControlAuditRoute,
  ControlChatRoute: ControlChatRoute,
  ControlCustomersRoute: ControlCustomersRoute,
  ControlDomainRoute: ControlDomainRoute,
  ControlEmailRoute: ControlEmailRoute,
  ControlIntegrationsRoute: ControlIntegrationsRoute,
  ControlLinksRoute: ControlLinksRoute,
  ControlParametersRoute: ControlParametersRoute,
  ControlRequestsRoute: ControlRequestsRoute,
  ControlResourcesRoute: ControlResourcesRoute,
  ControlShortsRoute: ControlShortsRoute,
  ControlStatsRoute: ControlStatsRoute,
  ControlWorkspaceRoute: ControlWorkspaceRoute,
  ControlIndexRoute: ControlIndexRoute,
}

const ControlRouteWithChildren =
  ControlRoute._addFileChildren(ControlRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ControlRoute: ControlRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCardsResourceIdRoute: ApiCardsResourceIdRoute,
  ApiFilesResourceIdRoute: ApiFilesResourceIdRoute,
  ApiV1ShortsRoute: ApiV1ShortsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
